{{- if and .Values.secret_store.name .Values.external_secrets.remote_key }}
apiVersion: {{ .Values.external_secrets.api_version }}
kind: ExternalSecret
metadata:
  name: {{ .Values.env_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/release-name: "{{ .Release.Name }}"
    helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/release-revision: "{{ .Release.Revision }}"
spec:
  refreshPolicy: {{ .Values.external_secrets.refresh_policy }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.env_secret }}
    creationPolicy: Owner
  data:
  - secretKey: install_bundle
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.install_bundle }}
  - secretKey: ws_address
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.ws_address }}
{{- else if and .Values.install_bundle .Values.ws_address }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env_secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  install_bundle: {{ .Values.install_bundle | b64enc }}
  ws_address: {{ .Values.ws_address | b64enc }}
{{- end }}
