{{- if and .Values.secret_store.name .Values.secret_store.secrets.remote_key }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.env_secret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secret_store.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.env_secret }}
    creationPolicy: Owner
  data:
  - secretKey: install_bundle
    remoteRef:
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: INSTALL_BUNDLE
  - secretKey: ws_address
    remoteRef:
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: WS_ADDRESS
{{- else}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env_secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  install_bundle: {{ .Values.install_bundle }}
  ws_address: {{ .Values.ws_address }}
{{- end}}