{{- if .Values.image_pull_secret }}
{{- if and .Values.secret_store.name .Values.secret_store.remote_key }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.image_pull_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/release-name: "{{ .Release.Name }}"
    helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/release-revision: "{{ .Release.Revision }}"
spec:
  refreshInterval: {{ .Values.secret_store.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.image_pull_secret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{\"auths\":{\"{{ "{{" }} .registry | lower {{ "}}" }}\":{\"username\":\"{{ "{{" }} .username {{ "}}" }}\",\"password\":\"{{ "{{" }} .password {{ "}}" }}\"}}}"
  data:
  - secretKey: registry
    remoteRef:
      key: {{ .Values.secret_store.remote_key }}
      property: {{ .Values.secret_store.properties_name.registry }}
  - secretKey: username
    remoteRef:
      key: {{ .Values.secret_store.remote_key }}
      property: {{ .Values.secret_store.properties_name.username }}
  - secretKey: password
    remoteRef:
      key: {{ .Values.secret_store.remote_key }}
      property: {{ .Values.secret_store.properties_name.password }}
{{- else if or (.Values.registry.dockerconfigjson) (and .Values.registry.name .Values.registry.username .Values.registry.password) }}
apiVersion: v1
data:
  {{- if .Values.registry.dockerconfigjson }}
  .dockerconfigjson: {{ .Values.registry.dockerconfigjson }}
  {{- else }}
  .dockerconfigjson: {{printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry.name (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .Values.image_pull_secret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}
