{{- if or (.Values.registry.dockerconfigjson) (and .Values.registry.name .Values.registry.username .Values.registry.password) }}
apiVersion: v1
data:
  {{- if .Values.registry.dockerconfigjson }}
  .dockerconfigjson: {{ .Values.registry.dockerconfigjson }}
  {{- else }}
  .dockerconfigjson: {{printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry.name (printf "%s:%s" .Values.registry.username .Values.registry.password | b64enc) | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .Values.image_pull_secret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}