{{- if and .Values.secret_store.name .Values.secret_store.remote_key }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.twistlock_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/release-name: "{{ .Release.Name }}"
    helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/release-revision: "{{ .Release.Revision }}"
spec:
  refreshInterval: {{ .Values.secret_store.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.twistlock_secret }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        service-parameter: "{{ "{{" }} .service_parameter | b64dec {{ "}}" }}"
        defender-ca.pem: "{{ "{{" }} .defender_ca | b64dec {{ "}}" }}"
        defender-client-cert.pem: "{{ "{{" }} .defender_client_cert | b64dec {{ "}}" }}"
        defender-client-key.pem: "{{ "{{" }} .defender_client_key | b64dec {{ "}}" }}"
        admission-cert.pem: "{{ "{{" }} .admission_cert | b64dec {{ "}}" }}"
        admission-key.pem: "{{ "{{" }} .admission_key | b64dec {{ "}}" }}"
  data:
  - secretKey: service_parameter
    remoteRef:
      key: {{ .Values.secret_store.remote_key }}
      property: SERVICE_PARAMETER
  - secretKey: defender_ca
    remoteRef:
      key: {{ .Values.secret_store.remote_key }}
      property: DEFENDER_CA
  - secretKey: defender_client_cert
    remoteRef: 
      key: {{ .Values.secret_store.remote_key }}
      property: DEFENDER_CLIENT_CERT
  - secretKey: defender_client_key
    remoteRef: 
      key: {{ .Values.secret_store.remote_key }}
      property: DEFENDER_CLIENT_KEY
  - secretKey: admission_cert
    remoteRef: 
      key: {{ .Values.secret_store.remote_key }}
      property: ADMISSION_CERT
  - secretKey: admission_key
    remoteRef: 
      key: {{ .Values.secret_store.remote_key }}
      property: ADMISSION_KEY
{{- else}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.twistlock_secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  service-parameter: {{ .Values.service_parameter }}
  defender-ca.pem: {{ .Values.defender_ca_cert }}
  defender-client-cert.pem: {{ .Values.defender_client_cert }}
  defender-client-key.pem: {{ .Values.defender_client_key }}
{{- if .Values.old_defender_ca_cert }}
  defender-ca.pem.old: {{ .Values.old_defender_ca_cert }}
  defender-client-cert.pem.old: {{ .Values.old_defender_client_cert }}
  defender-client-key.pem.old: {{ .Values.old_defender_client_key }}
{{- end}}
  admission-cert.pem: {{ .Values.admission_cert }}
  admission-key.pem: {{ .Values.admission_key }}
{{if .Values.access_ca}}
  access-ca.pem: {{ .Values.access_ca }}
{{- end}}
{{- end}}