{{- if and .Values.secret_store.name .Values.external_secrets.remote_key }}
apiVersion: {{ .Values.external_secrets.api_version }}
kind: ExternalSecret
metadata:
  name: {{ .Values.twistlock_secret }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/release-name: "{{ .Release.Name }}"
    helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/release-revision: "{{ .Release.Revision }}"
spec:
  refreshPolicy: {{ .Values.external_secrets.refresh_policy }}
  refreshInterval: {{ .Values.external_secrets.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.twistlock_secret }}
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: service_parameter
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.service_parameter }}
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
  - secretKey: defender_ca
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.defender_ca }}
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
  - secretKey: defender_client_cert
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.defender_client_cert }}
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
  - secretKey: defender_client_key
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.defender_client_key }}
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
  - secretKey: admission_cert
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.admission_cert }}
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
  - secretKey: admission_key
    remoteRef:
      key: {{ .Values.external_secrets.remote_key }}
      property: {{ .Values.external_secrets.properties_name.admission_key }}
      conversionStrategy: Default
      decodingStrategy: Base64
      metadataPolicy: None
{{- else if and .Values.service_parameter .Values.defender_ca_cert .Values.defender_client_cert .Values.defender_client_key .Values.admission_cert .Values.admission_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.twistlock_secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  service-parameter: {{ .Values.service_parameter }}
  defender-ca.pem: {{ .Values.defender_ca_cert }}
  defender-client-cert.pem: {{ .Values.defender_client_cert }}
  defender-client-key.pem: {{ .Values.defender_client_key }}
{{- if .Values.old_defender_ca_cert }}
  defender-ca.pem.old: {{ .Values.old_defender_ca_cert }}
  defender-client-cert.pem.old: {{ .Values.old_defender_client_cert }}
  defender-client-key.pem.old: {{ .Values.old_defender_client_key }}
{{- end }}
  admission-cert.pem: {{ .Values.admission_cert }}
  admission-key.pem: {{ .Values.admission_key }}
{{if .Values.access_ca}}
  access-ca.pem: {{ .Values.access_ca }}
{{- end }}
{{- end }}
