{{- if and .Values.secret_store.name .Values.secret_store.secrets.remote_key }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.twistlock_secret }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.secret_store.refresh_interval }}
  secretStoreRef:
    name: {{ .Values.secret_store.name }}
    kind: {{ .Values.secret_store.kind }}
  target:
    name: {{ .Values.twistlock_secret }}
    creationPolicy: Owner
  data:
  - secretKey: service-parameter
    remoteRef:
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: SERVICE_PARAMETER
  - secretKey: defender-ca.pem
    remoteRef:
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: DEFENDER_CA
  - secretKey: defender-client-cert.pem
    remoteRef: 
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: DEFENDER_CLIENT_CERT
  - secretKey: defender-client-key.pem
    remoteRef: 
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: DEFENDER_CLIENT_KEY
  - secretKey: admission-cert.pem
    remoteRef: 
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: ADMISSION_CERT
  - secretKey: admission-key.pem
    remoteRef: 
      key: {{ .Values.secret_store.secrets.remote_key }}
      property: ADMISSION_KEY
{{- else}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.twistlock_secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  service-parameter: {{ .Values.service_parameter }}
  defender-ca.pem: {{ .Values.defender_ca_cert }}
  defender-client-cert.pem: {{ .Values.defender_client_cert }}
  defender-client-key.pem: {{ .Values.defender_client_key }}
{{- if .Values.old_defender_ca_cert }}
  defender-ca.pem.old: {{ .Values.old_defender_ca_cert }}
  defender-client-cert.pem.old: {{ .Values.old_defender_client_cert }}
  defender-client-key.pem.old: {{ .Values.old_defender_client_key }}
{{- end}}
  admission-cert.pem: {{ .Values.admission_cert }}
  admission-key.pem: {{ .Values.admission_key }}
{{if .Values.access_ca}}
  access-ca.pem: {{ .Values.access_ca }}
{{- end}}
{{- end}}