{{- if and .Values.admission_path .Values.defender_ca_cert }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "tw-validating-webhook"
webhooks:
  - name: "validating-webhook.twistlock.com"
    # namespaceSelector
    # matchPolicy: Equivalent # v1.15+
    # timeoutSeconds: 2 # v1.14+
    admissionReviewVersions: ["v1", "v1beta1"] # Specify what versions of AdmissionReview objects are accepted
    sideEffects: None # sideEffects must be set to None or NoneOnDryRun
    failurePolicy: Ignore # Default failurePolicy is Fail
    rules:
      - operations: 
        - "CREATE"
        - "UPDATE"
        - "CONNECT"
        {{- if .Values.admission_add_delete }}
        - "DELETE"
        {{- end }}
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*/*"]
    clientConfig:
      # caBundle field should be similar to the CA bundle from the Defender DaemonSet YAML. Make sure to change it if you are using an older Defender CA.
      caBundle: "{{ .Values.defender_ca_cert }}"
      service:
        name: defender
        namespace: {{ .Release.Namespace }}
        path: {{ .Values.admission_path }}
{{- end }}