DATA_FOLDER: /var/lib/twistlock
FIPS_ENABLED: "false"
access_ca: ""
admission_cert: 
admission_key: 
cluster: ""
cluster_name_resolving_method: default
cluster_role_name: twistlock-view
collect_pod_labels: true
container_runtime_socket_folder: /var/run
containers_storage_mount: /var/lib/containerd
containers_storage_mount_rke2: /var/lib/rancher/rke2/agent/containerd
cri_data_rke2_volume_name: cri-rke2-data
cri_data_volume_name: cri-data
defender_ca_cert: 
defender_client_cert: 
defender_client_key: 
defender_service_port: 9998
defender_type: cri
docker_socket_path: /var/run/docker.sock
gke_autopilot_annotation: ""
host_custom_compliance: true
twistlock_secret: twistlock-secrets
image_name: 
registry:
  name: 
  username: 
  password:
  dockerconfigjson:
install_bundle: 
limit_cpu: '"900m"'
limit_memory: '"512Mi"'
monitor_istio: false
monitor_service_accounts: true
node_selector: ""
old_defender_ca_cert: ""
old_defender_client_cert: ""
old_defender_client_key: ""
openshift: false
privileged: "false"
role_arn: ""
runc_proxy_sock_folder: /run
image_pull_secret: twistlock-pull-secret
env_secret: twistlock-env-secrets
secret_store:                         # Integrate with External Secrets Operator 
  name:                               # Name of the Secrets Store where the Access to Prisma is located
  kind: ClusterSecretStore            # Secrets Store kind
  refresh_interval: 1h                # Secrets refresh interval
  pull_secret:
    remote_key:                       # Remote secret name for extracting the registry image
  secrets:
    remote_key:                       # Remote secret name for extracting the Defender secrets
selinux_header: ""
selinux_options: ""
service_parameter: 
talos: false
twistlock_data_folder: /var/lib/twistlock
unique_hostname: true
ws_address: